#!/usr/bin/env bash
set -euo pipefail

wallpaper_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/wallpapers"
state_dir="${XDG_CACHE_HOME:-$HOME/.cache}/swww"

img_path="$(find "${wallpaper_dir}" -maxdepth 1 -type f | shuf -n 1)"
mkdir -p "${state_dir}"
cp "${img_path}" "${state_dir}/curent_walpaper.jpg"

exec swww img "${img_path}" --transition-fps 10 --transition-type random --transition-step 200
