#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts
wallpaper="$config/wallpapers/home-sweet-home.jpg"

# waybar
$scripts/launch_waybar &

# wallpaper set to cloud.png
#swww init && swww img $HOME/.config/hypr/wallpapers/home-sweet-home.jpg --transition-type center --transition-fps 60 --transition-speed 16

# Запускаем swww-daemon
swww-daemon &

# Ждём, пока сокет появится (максимум 5 секунд)
timeout=5
while [ $timeout -gt 0 ]; do
    if pgrep -x swww-daemon > /dev/null && [ -S "/tmp/swww.socket" ]; then
        break
    fi
    sleep 0.2
    ((timeout--))
done

# Устанавливаем обои
swww img "$wallpaper" --transition-type center --transition-fps 60 --transition-speed 16




# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
Telegram &
slimbookbattery --minimize &
