local map = vim.keymap.set
local opts = { silent = true }

local function nmap(lhs, rhs, desc)
  map("n", lhs, rhs, vim.tbl_extend("force", { desc = desc }, opts))
end

nmap("<Esc><Esc>", ":let @/ = ''<CR>", "Clear search")
nmap("<C-b>", ":Neotree toggle<CR>", "Toggle explorer")
nmap("<leader>b", ":Neotree toggle<CR>", "Toggle explorer")
nmap("<C-f>", ":Neotree reveal<CR>", "Reveal file in explorer")
nmap("<C-t>", ":tabnew<CR>", "New tab")
nmap("<C-h>", ":tabprevious<CR>", "Previous tab")
nmap("<C-l>", ":tabnext<CR>", "Next tab")
nmap("<C-c>", ":tabclose<CR>", "Close tab")
nmap("<F5>", ":make<CR>", "Make")
nmap("<F6>", ":AsyncRun cmake --build build<CR>", "Build project")
nmap("<C-s>", ":wa<CR>", "Save all")
nmap("<F7>", ":ToggleTerm direction=horizontal size=15<CR>", "Toggle terminal")
nmap("<leader>ff", "<Cmd>Telescope find_files<CR>", "Find files")
nmap("<leader>fg", "<Cmd>Telescope live_grep<CR>", "Live grep")
nmap("<leader>fb", "<Cmd>Telescope buffers<CR>", "Buffers")
nmap("<leader>fh", "<Cmd>Telescope help_tags<CR>", "Help tags")
nmap("<leader>e", "<Cmd>Neotree toggle<CR>", "Explorer")
nmap("<leader>gb", "<Cmd>Gitsigns toggle_current_line_blame<CR>", "Toggle blame")
nmap("<leader>rn", "<Cmd>lua vim.lsp.buf.rename()<CR>", "LSP rename")
nmap("<leader>gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", "Go to definition")
nmap("<leader>lf", "<Cmd>lua require('conform').format({ async = true, lsp_fallback = true })<CR>", "Format buffer")
nmap("<leader>xx", "<Cmd>Trouble diagnostics toggle<CR>", "Trouble diagnostics")
nmap("<leader>xd", "<Cmd>Trouble diagnostics toggle filter.buf=0<CR>", "Trouble buffer diagnostics")
nmap("<leader>xq", "<Cmd>Trouble qflist toggle<CR>", "Trouble quickfix")
nmap("<leader>xl", "<Cmd>Trouble loclist toggle<CR>", "Trouble loclist")
map("n", "<leader>/", "<cmd>lua require('Comment.api').toggle.linewise.current()<CR>", { desc = "Toggle comment", silent = true })
map("v", "<leader>/", "<Esc><cmd>lua require('Comment.api').toggle.linewise(vim.fn.visualmode())<CR>", { desc = "Toggle comment selection", silent = true })
